### ISSUE TITLE
DOMNodeInserted: event.relatedNode is null

### ISSUE THREAD

**Issue by peterzanetti** [mfreed7/mutation-events-polyfill#2]
After adding the polyfill and using it with code previously working with DOMNodeInserted, the event.relatedNode is null.

**Comment by mfreed7** [comment]
Yeah, I agree that's a point that the polyfill doesn't fully address. I just [updated the README](https://github.com/mfreed7/mutation-events-polyfill#:~:text=Finally%2C%20the%20relatedNode%20field%20of%20the%20dispatched%20events) (and a bit of the tests) to acknowledge that.

There is some code to add `relatedNode`, but it doesn't always work:
https://github.com/mfreed7/mutation-events-polyfill/blob/main/src/mutation_events.js#L54

I'm very open to pull requests, if you want to take a look at adding better support for `relatedNode`!
